#- pipeline.id: normal-beats
#  path.config: "/usr/share/logstash/pipeline/logstash.conf"
#  pipeline.workers: 3
- pipeline.id: lktransfer
  path.config: "/usr/share/logstash/pipeline/logstash-crsp.conf"
  queue.type: persisted