## Cluster Settings
cluster.name: "elk-tls-cluster"
network.host: "0.0.0.0"
#http.host: 0.0.0.0
node.name: "elasticsearch02"
discovery.seed_hosts: ["elasticsearch01","elasticsearch03"]
cluster.initial_master_nodes: ["elasticsearch01","elasticsearch02","elasticsearch03"]


## License
xpack.license.self_generated.type: trial

# Security
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
xpack.security.authc.token.enabled: true
xpack.security.authc.api_key.enabled: true

# transport security settings
# This is mostly used for inter-node communications between parts of the ELK stack
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key: ${CONFIG_DIR}/elasticsearch02.key
xpack.security.transport.ssl.certificate: ${CONFIG_DIR}/elasticsearch02.crt
xpack.security.transport.ssl.certificate_authorities: ${CONFIG_DIR}/ca.crt
xpack.security.transport.ssl.verification_mode: certificate
# HTTP security setttings
# This is used for client server ssl/tls communications (e.g. browser to kibana)
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: ${CONFIG_DIR}/elasticsearch02.key
xpack.security.http.ssl.certificate: ${CONFIG_DIR}/elasticsearch02.crt
xpack.security.http.ssl.certificate_authorities: ${CONFIG_DIR}/ca.crt
